In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df2014 = pd.read_csv('finance_data/2014_Financial_Data.csv')
df2015 = pd.read_csv('finance_data/2015_Financial_Data.csv')
df2016 = pd.read_csv('finance_data/2016_Financial_Data.csv')
df2017 = pd.read_csv('finance_data/2017_Financial_Data.csv')
df2018 = pd.read_csv('finance_data/2018_Financial_Data.csv')

In [4]:
df2014.head()

,Unnamed: 0,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2015 PRICE VAR [%],Class
0,PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.000000e+00,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,...,-0.0187,-0.0217,0.0359,0.0316,0.1228,0.0000,-0.1746,Consumer Defensive,-9.323276,0
1,VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,1.083303e+08,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,...,NaN,NaN,NaN,NaN,NaN,1.6484,1.7313,Consumer Defensive,-25.512193,0
2,KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.000000e+00,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,...,0.0618,0.0981,0.1886,0.3268,0.2738,0.0000,0.0234,Consumer Defensive,33.118297,1
3,RAD,2.552641e+10,0.0053,1.820268e+10,7.323734e+09,0.000000e+00,6.561162e+09,6.586482e+09,7.372520e+08,4.245910e+08,...,0.0211,-0.0510,-0.0189,0.1963,-0.0458,0.0000,-0.0060,Consumer Defensive,2.752291,1
4,GIS,1.790960e+10,0.0076,1.153980e+10,6.369800e+09,0.000000e+00,3.474300e+09,3.412400e+09,2.957400e+09,3.024000e+08,...,0.0257,0.0090,0.0215,0.0274,0.1025,0.0000,-0.0220,Consumer Defensive,12.897715,1

In [10]:
df2014.isnull().sum()

Unnamed: 0                0
Revenue                  44
Revenue Growth          236
Cost of Revenue          74
Gross Profit             52
                       ...
R&D Expense Growth      247
SG&A Expenses Growth    243
Sector                    0
2015 PRICE VAR [%]        0
Class                     0
Length: 225, dtype: int64

In [14]:
df2014.fillna(0 , inplace =True)
df2015.fillna(0 , inplace =True)
df2016.fillna(0 , inplace =True)
df2017.fillna(0 , inplace =True)
df2018.fillna(0 , inplace =True)
df2018.isnull().sum()

name                    0
Revenue                 0
Revenue Growth          0
Cost of Revenue         0
Gross Profit            0
                       ..
R&D Expense Growth      0
SG&A Expenses Growth    0
Sector                  0
2019 PRICE VAR [%]      0
Class                   0
Length: 225, dtype: int64

In [15]:
df2014.rename(columns={df2014.columns[0] : 'name'} , inplace = True)
df2015.rename(columns={df2015.columns[0] : 'name'} , inplace = True)
df2016.rename(columns={df2016.columns[0] : 'name'} , inplace = True)
df2017.rename(columns={df2017.columns[0] : 'name'} , inplace = True)
df2018.rename(columns={df2018.columns[0] : 'name'} , inplace = True)

In [28]:
df2018['name'].unique()
df2018.shape

(4392, 225)

In [35]:
dfall4= pd.merge(df2014,df2015 , on ='name' , how='inner')
dfall4.head()

,name,Revenue_x,Revenue Growth_x,Cost of Revenue_x,Gross Profit_x,R&D Expenses_x,SG&A Expense_x,Operating Expenses_x,Operating Income_x,Interest Expense_x,...,Receivables growth_y,Inventory Growth_y,Asset Growth_y,Book Value per Share Growth_y,Debt Growth_y,R&D Expense Growth_y,SG&A Expenses Growth_y,Sector_y,2016 PRICE VAR [%],Class_y
0,PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.000000e+00,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,...,-0.2847,-0.2634,-0.1024,-0.1013,-0.1432,0.0000,-0.0394,Consumer Defensive,10.809451,1
1,VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,1.083303e+08,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,...,28.6759,0.2144,0.1279,0.2946,0.0281,0.5309,0.5179,Consumer Defensive,-21.637010,0
2,KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.000000e+00,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,...,0.1344,0.0065,0.0415,0.0535,0.0254,0.0000,0.1293,Consumer Defensive,-15.036503,0
3,RAD,2.552641e+10,0.0053,1.820268e+10,7.323734e+09,0.000000e+00,6.561162e+09,6.586482e+09,7.372520e+08,4.245910e+08,...,0.0336,-0.0371,0.2639,1.0266,-0.0344,0.0000,0.0205,Consumer Defensive,4.303799,1
4,GIS,1.790960e+10,0.0076,1.153980e+10,6.369800e+09,0.000000e+00,3.474300e+09,3.412400e+09,2.957400e+09,3.024000e+08,...,-0.0653,-0.0119,-0.0568,-0.2118,0.0462,0.0000,-0.0421,Consumer Defensive,10.693172,1

In [21]:
dfall = pd.concat([df2014,df2015,df2016,df2017,df2018])
dfall.shape

(22077, 229)

In [23]:
dfall.fillna(0,inplace=True)
dfall.isnull().sum()

Unnamed: 0            0
Revenue               0
Revenue Growth        0
Cost of Revenue       0
Gross Profit          0
                     ..
Class                 0
2016 PRICE VAR [%]    0
2017 PRICE VAR [%]    0
2018 PRICE VAR [%]    0
2019 PRICE VAR [%]    0
Length: 229, dtype: int64

In [55]:
years =[2014,2015,2016,2017,2018]
quickratio_year= list([0,0,0,0,0])
i = 0
for y  in years :
   quickratio_year[i] = dfall.groupby(f'{y} PRICE VAR [%]')
   i+=1

quickratio_year[0]

plt.figure(figsize=(10,10))
y= dfall['quickRatio']
x= years
plt.bar(x,y)

KeyError: '2014 PRICE VAR [%]'

In [48]:
y=2016
h=list([0,0,0,0])
h[0] =dfall.groupby(f'{y} PRICE VAR [%]')
#h[0].head(3)
yy=2017
h[1] =dfall.groupby(f'{yy} PRICE VAR [%]')
h[1].head(3)

,Unnamed: 0,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,...,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2015 PRICE VAR [%],Class,2016 PRICE VAR [%],2017 PRICE VAR [%],2018 PRICE VAR [%],2019 PRICE VAR [%]
0,PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.000000e+00,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,...,0.1228,0.0000,-0.1746,Consumer Defensive,-9.323276,0,0.0,0.000000,0.0,0.0
1,VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,1.083303e+08,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,...,0.0000,1.6484,1.7313,Consumer Defensive,-25.512193,0,0.0,0.000000,0.0,0.0
2,KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.000000e+00,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,...,0.2738,0.0000,0.0234,Consumer Defensive,33.118297,1,0.0,0.000000,0.0,0.0
0,PG,6.529900e+10,-0.0770,3.290900e+10,3.239000e+10,0.000000e+00,1.894900e+10,1.894900e+10,1.344100e+10,5.790000e+08,...,0.0083,0.0000,-0.0809,Consumer Defensive,0.000000,1,0.0,12.532463,0.0,0.0
1,VIPS,8.148496e+09,0.3156,6.190740e+09,1.957756e+09,2.251378e+08,6.880959e+08,1.567877e+09,3.898789e+08,1.226710e+07,...,-0.0139,0.3575,0.3172,Consumer Defensive,0.000000,1,0.0,4.363319,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4792,TSRI,6.099828e+07,0.0626,5.103888e+07,9.959402e+06,0.000000e+00,9.120526e+06,9.120526e+06,8.388760e+05,0.000000e+00,...,0.0000,0.0000,0.0267,Technology,0.000000,1,0.0,0.655807,0.0,0.0
4793,TZOO,1.142630e+08,-0.0782,1.385500e+07,1.004080e+08,9.096000e+06,8.112600e+07,9.022200e+07,1.018600e+07,0.000000e+00,...,-1.0000,-0.2553,-0.0964,Technology,0.000000,0,0.0,-35.500002,0.0,0.0
4794,USATP,7.700000e+07,0.0000,5.500000e+07,2.200000e+07,0.000000e+00,2.200000e+07,2.300000e+07,-1.000000e+06,1.000000e+06,...,0.0000,0.0000,0.0000,Technology,0.000000,1,0.0,14.840183,0.0,0.0
4795,WSTG,1.646090e+08,-0.5692,1.372780e+08,2.733100e+07,0.000000e+00,1.871500e+07,1.871500e+07,8.616000e+06,-3.180000e+05,...,0.0000,0.0000,0.0361,Technology,0.000000,0,0.0,-2.854095,0.0,0.0
4796,WTT,3.132700e+07,-0.0538,1.816500e+07,1.316200e+07,4.046000e+06,1.166400e+07,1.571000e+07,-2.548000e+06,0.000000e+00,...,-1.0000,0.0224,0.1522,Technology,0.000000,1,0.0,29.946527,0.0,0.0

In [29]:
dfall.groupby('2016 PRICE VAR [%]').head(3)

,Unnamed: 0,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,...,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2015 PRICE VAR [%],Class,2016 PRICE VAR [%],2017 PRICE VAR [%],2018 PRICE VAR [%],2019 PRICE VAR [%]
0,PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.000000e+00,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,...,0.1228,0.0000,-0.1746,Consumer Defensive,-9.323276,0,0.000000,0.0,0.0,0.0
1,VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,1.083303e+08,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,...,0.0000,1.6484,1.7313,Consumer Defensive,-25.512193,0,0.000000,0.0,0.0,0.0
2,KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.000000e+00,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,...,0.2738,0.0000,0.0234,Consumer Defensive,33.118297,1,0.000000,0.0,0.0,0.0
0,PG,7.074900e+10,-0.0491,3.705600e+10,3.369300e+10,0.000000e+00,2.061600e+10,2.264400e+10,1.104900e+10,6.260000e+08,...,-0.1432,0.0000,-0.0394,Consumer Defensive,0.000000,1,10.809451,0.0,0.0,0.0
1,VIPS,6.193685e+09,0.6587,4.669038e+09,1.524648e+09,1.658481e+08,5.223879e+08,1.205660e+09,3.189877e+08,1.321245e+07,...,0.0281,0.5309,0.5179,Consumer Defensive,0.000000,0,-21.637010,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,TSRI,5.740290e+07,0.1590,4.808743e+07,9.315468e+06,0.000000e+00,8.883003e+06,8.883003e+06,4.324650e+05,0.000000e+00,...,0.0000,0.0000,0.0763,Technology,0.000000,1,33.101842,0.0,0.0,0.0
4116,TZOO,1.239610e+08,-0.1911,1.814800e+07,1.058130e+08,1.221400e+07,8.977900e+07,1.019930e+08,3.820000e+06,0.000000e+00,...,4.6580,0.0784,-0.2021,Technology,0.000000,1,13.801445,0.0,0.0,0.0
4117,USATP,5.800000e+07,0.0000,4.100000e+07,1.700000e+07,0.000000e+00,1.600000e+07,1.700000e+07,-0.000000e+00,0.000000e+00,...,0.0000,0.0000,0.0000,Technology,0.000000,1,34.769228,0.0,0.0,0.0
4118,WSTG,3.820900e+08,0.1213,3.555170e+08,2.657300e+07,0.000000e+00,1.806300e+07,1.806300e+07,8.510000e+06,-3.680000e+05,...,0.0000,0.0000,0.0939,Technology,0.000000,1,6.050663,0.0,0.0,0.0
4119,WTT,3.310911e+07,-0.1792,1.828123e+07,1.482787e+07,3.957274e+06,1.012356e+07,1.408084e+07,7.470390e+05,0.000000e+00,...,1.3011,0.1708,-0.0784,Technology,0.000000,1,17.177912,0.0,0.0,0.0

In [ ]:
dfall['Year'] = pd.to_datetime(dfall[''])